### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by aracelicaes**
Pulling project to verify The Stickler.

### CODE REVIEW

**Review by Forison — COMMENTED** [review]
# Pull request under review by Addo

**Review by Forison — CHANGES_REQUESTED** [review]
# Hi @Araceli and @Gwen,👏
you have done a great job with this project. The project looks good and I can confidently say it 99% complete. I am curious🤔 about your choice of using  ID for selection in different instances.🙂

Let us make this tiny change and get our project approved🙂
 - [ ] TWN at Medium version changes logo appears at the leftmost part.🙂
currently, this what I get from the browser, 
Screenshot from 2019-11-05 15-49-12
the space for the logo is created by the logo itself is not there
 #### Kindly make this change and submit the project for review
feel free to contact me on [LinkedIn](https://www.linkedin.com/in/forison-addo-558201159/), [Twitter](https://twitter.com/ADDOBOAKYE1) or slack for further clarification if necessary. I would be happy to assist you.
### happy coding

**Comment by HeyItsGwen** [comment]
That logo is there, tested on two different computers with firefox and chrome on both. Link to image to show it working: https://files.slack.com/files-pri/T47CT8XPG-FPYT3QZSM/capture.png

**Comment by HeyItsGwen** [comment]
folder location in CSS wasn't capitalized the same as the folder location within the file system. For some reason it showed up on our end, but not after upload to github

**Comment by Anna-Myzukina** [comment]
#### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi Team!  
#### Wow, your project looks :+1: 

But need some Required Changes
#### Top 3 articles section
###### Small version changes

* [ ] All images take the maximum width and are are aligned in one column.



##### Footer
* [ ] Please check responsiveness:



Please remember that your branch name should be descriptive (e.g., refactor-authentication, user-content-cache-key, make-retina-avatars), so that others can see what is being worked on. You can read more about it [here](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/). I hope in the next project you can do this!

### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding 😄*

**Comment by HeyItsGwen** [comment]
Hi, can you clarify further? The top article section does take the full width, and show in a column, and the footer does change with break points. can you please be clearer on what needs changing?

**Comment by aracelicaes** [comment]
> 
> ### Hi Team! 
> #### Wow, your project looks 👍
> 
> But need some Required Changes
> #### Top 3 articles section
> ###### Small version changes
> 
>     * [ ]  All images take the maximum width and are are aligned in one column.
>       
> 
> 
> ##### Footer
> 
>     * [ ]  Please check responsiveness:
> 
> 
> 
> 
> Please remember that your branch name should be descriptive (e.g., refactor-authentication, user-content-cache-key, make-retina-avatars), so that others can see what is being worked on. You can read more about it [here](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/). I hope in the next project you can do this!
> ### Make changes and submit another code review request.
> 
> _If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you._
> _Happy coding 😄_

Hi! :) Sent you a message thru slack. So...when we see the responsive footer on the original page for ours it does change. Could you be a bit more specific please on what you mean?

**Comment by HeyItsGwen** [comment]
### PLEASE READ

Resubmitted for review. In the images the previous TSE is showing, the gap on the right is coming from the chrome dev tool mobile emulator, and doesn't actually exist on the page. If you examine the contents, you'll see the page width is the same as the emulator width, and the contents are in fact the full width.

The footer also resized with the page, and 'check responsiveness' isn't an instruction.

**Review by KaushikShivam — APPROVED** [review]
# Status: Approved 🎉 

Hello @aracelicaes & @HeyItsGwen,

Great job on implementing the changes required by the previous TSEs. I checked the previous issues on my device and they are alright. 👍 

## Congratualtions!! 
Go ahead and merge the branch. 
All the best for the next project.


Happy coding! 😄 
[Shivam Kaushik](https://github.com/KaushikShivam)
[Github](https://github.com/KaushikShivam) [Twitter](https://twitter.com/kShivamDev) [Linkedin](https://www.linkedin.com/in/shivam-kaushik-bb8162102/)

**Pull request merged**
